# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpeedyKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'GTMBase64', '~> 1.0.1'
  # Pods for SpeedyKit

end
